### PR TITLE
kube-aws: Improve stack creation failed error messaging

### LINKED ISSUE #430: kube-aws: Provide more contexts on stack creation failed?
Hi, Thanks for sharing this!

I have just encountered the following error on `kube-aws up`:

```
$ kube-aws up
Creating AWS resources. This should take around 5 minutes.
Error: Error creating cluster: Stack creation failed: CREATE_FAILED : The following resource(s) failed to create: [VPC, IAMRoleController, InternetGateway, IAMRoleWorker].
```

Looking into AWS console revealed that its cause was that CloudFormation failed to create a `AWS::EC2::InternetGateway`:
image

It was not very obvious just reading the message from `kube-aws`.
I guess if we could provide more context one can deal with errors more quickly.

Without thinking much, something like the following seems helpful for me:

> Stack creation failed.
> Printing recent events from Cfn which may or may not indicate what was problem:
> *snip*
> CREATE_FAILED	AWS::EC2::InternetGateway	InternetGateway	The maximum number of internet gateways has been reached.

Any thoughts?

### PR DESCRIPTION
**Pull request by cgag**
Previously you were only told which resources cloudformation failed to
create.  We now print the event details associated with each failure.

sample output:

2016-05-03-134713_959x209_scrot

fixes #430

### CODE REVIEW

**Comment by mumoshu** [comment]
@cgag I'm impressed with the informative error output.
I believe it will keep saving time for the rest of our lives 👍

File: multi-node/aws/pkg/cluster/cluster.go [hunk 1]
```diff
@@ -337,3 +352,25 @@ func (c *Cluster) validateDNSConfig(r53 r53Service) error {
...
 	return nil
 }
+
+func stackEventErrMsgs(events []*cloudformation.StackEvent) []string {
+	var errMsgs []string
+
+	for _, event := range events {
+		if aws.StringValue(event.ResourceStatus) == cloudformation.ResourceStatusCreateFailed {
+			// Only show actual failures, not cancelled dependent resources.
+			if aws.StringValue(event.ResourceStatusReason) != "Resource creation cancelled" {
```
Comment (aaronlevy) [inline multi-node/aws/pkg/cluster/cluster.go]: Why suppress cancellation errors?

**Comment by aaronlevy** [comment]
One question, but otherwise LGTM

File: multi-node/aws/pkg/cluster/cluster.go (hunk 1 above)
Comment (cgag) [inline multi-node/aws/pkg/cluster/cluster.go]: A failure to create a resource causes cancellation failures for the resources that depend on it, which don't help with debugging. I wanted to only show root causes.

If you or @colhom or @mumoshu think showing the cancellations is worth while, I can remove that check.

Comment (aaronlevy) [inline multi-node/aws/pkg/cluster/cluster.go]: That makes sense. I'm fine with ignoring them. And if a user triggers a cancellation, they should likely know why it failed :)

Comment (colhom) [inline multi-node/aws/pkg/cluster/cluster.go]: Agreed on that. I can't say I've ever tripped on that one.

**Comment by colhom** [comment]
@cgag rebase please.

**Comment by cgag** [comment]
rebased

**Comment by colhom** [comment]
on behalf of first-time users of kube-aws, thank you @cgag ;)
